name: production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy with docker compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            whoami
            cd /home/udin/fun/telenta-laravel
            git pull
            ./vendor/bin/sail npm install --no-save
            ./vendor/bin/sail npm run build
            ./vendor/bin/sail php artisan migrate
            ./vendor/bin/sail php artisan db:seed
            docker restart telenta-web
